#!/bin/bash

PROG=install.sh
USAGE="$PROG file"
DESC="Installs scenery generated by osm2city.py"
HELP="Merges osm2city's .stg with existing .stg files. Previous osm2city scenery is overwritten.
Scenery from other sources is retained."
AUTHOR="Thomas Albrecht"

[ "$1" == "-h" ] || [ "$1" == "--help" ] && \
    echo -e "Usage: $USAGE\n$DESC\n$HELP" && exit 1

set -u

# -- ATTENTION: You need to adjust $prefix and $tgt!
#    $tgt must point to your actual $prefix scenery tile folder,
#    e.g. /home/user/Scenery/Objects/e10n40/e011n47
prefix=LOWI
tgt=e011n47

rm $tgt/${prefix}city*.ac $tgt/${prefix}city*.xml

# mv ln/city-* e013n51/
cp ${prefix}city*.ac  $tgt/
cp ${prefix}city*.xml $tgt/
#kate city.stg $tgt/$stg

for stg in *.stg; do

    tmp=stg.tmp

    sed -e '/# osm2city/,$d' $tgt/$stg > $tmp
    cat $tmp $stg > $tgt/$stg
    #mv $tmp $tgt/$stg # -- uninstall
    #kate $tgt/$stg &
done
