"""Holds string constants for OSM keys and values."""

# ======================= KEYS ====================================
K_AERIALWAY = 'aerialway'
K_AEROWAY = 'aeroway'
K_AMENITY = 'amenity'
K_AREA = 'area'
K_BRIDGE = 'bridge'
K_BUILDING = 'building'
K_BUILDING_COLOUR = 'building:colour'
K_BUILDING_HEIGHT = 'building:height'
K_BUILDING_LEVELS = 'building:levels'
K_BUILDING_MATERIAL = 'building:material'
K_BUILDING_PART = 'building:part'
K_CABLES = 'cables'
K_CONTENT = 'content'
K_DENOMINATION = 'denomination'
K_ELECTRIFIED = 'electrified'
K_GAUGE = 'gauge'
K_GENERATOR_TYPE = 'generator:type'
K_HEIGHT = 'height'
K_HIGHWAY = 'highway'
K_INDOOR = 'indoor'
K_JUNCTION = 'junction'
K_LANDUSE = 'landuse'
K_LANES = 'lanes'
K_LAYER = 'layer'
K_LEISURE = 'leisure'
K_LEVEL = 'level'
K_LEVELS = 'levels'
K_LIT = 'lit'
K_LOCATION = 'location'
K_MAN_MADE = 'man_made'
K_MANUFACTURER = 'manufacturer'
K_MANUFACTURER_TYPE = 'manufacturer_type'
K_MATERIAL = 'material'
K_MIN_HEIGHT = 'min_height'
K_MIN_HEIGHT_COLON = 'min:height'  # Incorrect value, but sometimes used
K_NAME = 'name'
K_NATURAL = 'natural'
K_OFFSHORE = 'offshore'
K_ONEWAY = 'oneway'
K_PARKING = 'parking'
K_PLACE = 'place'
K_PLACE_NAME = 'place_name'
K_POPULATION = 'population'
K_POWER = 'power'
K_PUBLIC_TRANSPORT = 'public_transport'
K_RAILWAY = 'railway'
K_RELIGION = 'religion'
K_ROOF_ANGLE = 'roof:angle'
K_ROOF_COLOUR = 'roof:colour'
K_ROOF_HEIGHT = 'roof:height'
K_ROOF_MATERIAL = 'roof:material'
K_ROOF_ORIENTATION = 'roof:orientation'
K_ROOF_SHAPE = 'roof:shape'
K_ROOF_SLOPE_DIRECTION = 'roof:slope:direction'
K_ROTOR_DIAMETER = 'rotor_diameter'
K_SEAMARK_LANDMARK_HEIGHT = 'seamark:landmark:height'
K_SEAMARK_LANDMARK_STATUS = 'seamark:landmark:status'
K_SEAMARK_STATUS = 'seamark:status'
K_SERVICE = 'service'
K_STRUCTURE = 'structure'
K_TRACKS = 'tracks'
K_TUNNEL = 'tunnel'
K_TYPE = 'type'
K_VOLTAGE = 'voltage'
K_WATERWAY = 'waterway'
K_WIKIDATA = 'wikidata'
K_WIRES = 'wires'

# ======================= VALUES ==================================
V_ACROSS = 'across'
V_AERODROME = 'aerodrome'
V_AERO_OTHER = 'aero_other'  # does not exist in OSM - used when it is unsure whether terminal, hangar or different
V_ALONG = 'along'
V_APRON = 'apron'
V_BRIDGE = 'bridge'
V_BUFFER_STOP = 'buffer_stop'
V_BUILDING = 'building'
V_CIRCULAR = 'circular'
V_CONTACT_LINE = 'contact_line'
V_DISUSED = 'disused'
V_FLAT = 'flat'
V_HANGAR = 'hangar'
V_INDOOR = 'indoor'
V_INNER = 'inner'
V_LIGHT_RAIL = 'light_rail'
V_MOTORWAY = 'motorway'
V_MULTIPOLYGON = 'multipolygon'
V_MULTISTOREY = 'multi-storey'
V_NARROW_GAUGE = 'narrow_gauge'
V_NO = 'no'
V_OUTER = 'outer'
V_OUTLINE = 'outline'
V_PIER = 'pier'
V_PLATFORM = 'platform'
V_PRESERVED = 'preserved'
V_RAIL = 'rail'
V_ROUNDABOUT = 'roundabout'
V_STORAGE_TANK = 'storage_tank'
V_SUBWAY = 'subway'
V_SWITCH = 'switch'
V_TANK = 'tank'
V_TERMINAL = 'terminal'
V_TOWER = 'tower'
V_TRAM = 'tram'
V_UNDERGROUND = 'underground'
V_WATER_TOWER = 'water_tower'
V_WAY = 'way'
V_YES = 'yes'

# ======================= KEY-VALUE PAIRS ==================================
KV_MAN_MADE_CHIMNEY = 'man_made=>chimney'
KV_ROUTE_FERRY = 'route=>ferry'


# ========================= NON OSM KEYS AND VALUES ===============
K_OWBB_GENERATED = 'owbb_generated'

V_GEN = 'gen'
